# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
# relative_permalinks: true

# Setup
title:               CRAFTSMAN
tagline:             LICHGO
description:         ''
url:                 http://jasonclinx.github.io
baseurl:             ''
paginate:            5
image_baseurl:       /assets/images

# About/contact
author:
  name:              jasonclinx
  url:               https://jasonclinx.github.io
  email:

# Custom vars
version:             1.0.0
gems:                [jekyll-paginate]
paginate_path:       "page:num"
excerpt_separator:   '<!--more-->'
